[[language]]
name = "rust"

[language-server.rust-analyzer]
environment.RUSTUP_TOOLCHAIN = "stable"

[language-server.rust-analyzer.config]
cargo.allTargets = false
cargo.target = "xtensa-esp32s3-none-elf"
check.extraEnv.RUSTUP_TOOLCHAIN = "esp"
cargo.extraEnv.RUSTUP_TOOLCHAIN = "esp"
